In [16]:
import os
import json
import requests
import pandas as pd

In [17]:
request_url = 'https://pokeapi.co/api/v2/generation/1'
response = requests.get(request_url)
response_1 = response.json()
with open ('../generation_1.json', 'w') as file: 
    json.dump(response_1,file)

gen_1_poke_df = pd.json_normalize(response_1, record_path = 'pokemon_species')
display(gen_1_poke_df)

           name                                             url
0     bulbasaur    https://pokeapi.co/api/v2/pokemon-species/1/
1    charmander    https://pokeapi.co/api/v2/pokemon-species/4/
2      squirtle    https://pokeapi.co/api/v2/pokemon-species/7/
3      caterpie   https://pokeapi.co/api/v2/pokemon-species/10/
4        weedle   https://pokeapi.co/api/v2/pokemon-species/13/
..          ...                                             ...
146     omastar  https://pokeapi.co/api/v2/pokemon-species/139/
147    kabutops  https://pokeapi.co/api/v2/pokemon-species/141/
148     snorlax  https://pokeapi.co/api/v2/pokemon-species/143/
149   dragonair  https://pokeapi.co/api/v2/pokemon-species/148/
150   dragonite  https://pokeapi.co/api/v2/pokemon-species/149/

[151 rows x 2 columns]

In [18]:
def extract_pokemon_id(url): 
    id = url.rstrip('/').split('/')[-1]
    return id

In [19]:
gen_1_poke_df['pokemon_id'] = gen_1_poke_df['url'].apply(extract_pokemon_id)
display(gen_1_poke_df)
gen_1_poke_df = gen_1_poke_df.sort_values('pokemon_id')

           name                                             url pokemon_id
0     bulbasaur    https://pokeapi.co/api/v2/pokemon-species/1/          1
1    charmander    https://pokeapi.co/api/v2/pokemon-species/4/          4
2      squirtle    https://pokeapi.co/api/v2/pokemon-species/7/          7
3      caterpie   https://pokeapi.co/api/v2/pokemon-species/10/         10
4        weedle   https://pokeapi.co/api/v2/pokemon-species/13/         13
..          ...                                             ...        ...
146     omastar  https://pokeapi.co/api/v2/pokemon-species/139/        139
147    kabutops  https://pokeapi.co/api/v2/pokemon-species/141/        141
148     snorlax  https://pokeapi.co/api/v2/pokemon-species/143/        143
149   dragonair  https://pokeapi.co/api/v2/pokemon-species/148/        148
150   dragonite  https://pokeapi.co/api/v2/pokemon-species/149/        149

[151 rows x 3 columns]

In [42]:
# THIS FUNCTION IS VERY INEFFICIENT - THIS VERSION IS FOR TESTING ONLY
def get_pokemon_species_details(pokemon_id): 
    request_url = f'https://pokeapi.co/api/v2/pokemon-species/{pokemon_id}'
    response = requests.get(request_url)
    data = response.json()
    if response.status_code != 200:
        print(f"Error: Received status code {response.status_code}")
        print(f"Response content: {response.text}")
    else:
        with open(f'../data/generation_1_pokemon_details/{pokemon_id}_species_details', 'w') as file:
            json.dump(data, file)
            species_details_df = pd.json_normalize(data)
    return species_details_df

get_pokemon_species_details(1)

,base_happiness,capture_rate,egg_groups,evolves_from_species,flavor_text_entries,form_descriptions,forms_switchable,gender_rate,genera,has_gender_differences,...,color.url,evolution_chain.url,generation.name,generation.url,growth_rate.name,growth_rate.url,habitat.name,habitat.url,shape.name,shape.url
0,50,45,"[{'name': 'monster', 'url': 'https://pokeapi.c...",None,[{'flavor_text': 'A strange seed was planted o...,[],False,1,"[{'genus': 'たねポケモン', 'language': {'name': 'ja-...",False,...,https://pokeapi.co/api/v2/pokemon-color/5/,https://pokeapi.co/api/v2/evolution-chain/1/,generation-i,https://pokeapi.co/api/v2/generation/1/,medium-slow,https://pokeapi.co/api/v2/growth-rate/4/,grassland,https://pokeapi.co/api/v2/pokemon-habitat/3/,quadruped,https://pokeapi.co/api/v2/pokemon-shape/8/

In [41]:

def get_pokemon_species_type(pokemon_id): 
    request_url = f'https://pokeapi.co/api/v2/type/{pokemon_id}'
    response = requests.get(request_url)
    data = response.json()
    if response.status_code != 200:
        print(f"Error: Received status code {response.status_code}")
        print(f"Response content: {response.text}")
    else:
        with open(f'../data/generation_1_pokemon_type_details/{pokemon_id}_type_details', 'w') as file:
            json.dump(data, file)
            species_type_df = pd.json_normalize(data)
    return species_type_df

get_pokemon_species_type(1)

,game_indices,id,moves,name,names,past_damage_relations,pokemon,damage_relations.double_damage_from,damage_relations.double_damage_to,damage_relations.half_damage_from,...,sprites.generation-v.black-2-white-2.name_icon,sprites.generation-v.black-white.name_icon,sprites.generation-vi.omega-ruby-alpha-sapphire.name_icon,sprites.generation-vi.x-y.name_icon,sprites.generation-vii.lets-go-pikachu-lets-go-eevee.name_icon,sprites.generation-vii.sun-moon.name_icon,sprites.generation-vii.ultra-sun-ultra-moon.name_icon,sprites.generation-viii.brilliant-diamond-and-shining-pearl.name_icon,sprites.generation-viii.legends-arceus.name_icon,sprites.generation-viii.sword-shield.name_icon
0,"[{'game_index': 0, 'generation': {'name': 'gen...",1,"[{'name': 'pound', 'url': 'https://pokeapi.co/...",normal,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",[],"[{'pokemon': {'name': 'pidgey', 'url': 'https:...","[{'name': 'fighting', 'url': 'https://pokeapi....",[],[],...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...

In [44]:
list_of_species_details_df = gen_1_poke_df['pokemon_id'].apply(get_pokemon_species_details)
species_details_df = pd.concat(list_of_species_details_df.to_list(), ignore_index=True)

list_of_species_type_df = gen_1_poke_df['pokemon_id'].apply(get_pokemon_species_type)
species_type_df = pd.concat(list_of_species_type_df.to_list(), ignore_index=True)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [38]:
species_details_df['habitat.name'].value_counts()

habitat.name
grassland        35
urban            22
forest           21
waters-edge      19
mountain         18
sea              15
rough-terrain     8
cave              8
rare              5
Name: count, dtype: int64