# NB2A - Pokemon Data Processing
This notebook

In [63]:
import json
import pandas as pd

In [64]:
with open('../../data/Pokemon Data/generation_1_pokemon.json', 'r') as file:
    generation_1_data = json.load(file)

gen_1_poke_df = pd.DataFrame(generation_1_data)
display(gen_1_poke_df)

           name                                             url  pokemon_id
0     bulbasaur    https://pokeapi.co/api/v2/pokemon-species/1/           1
1       ivysaur    https://pokeapi.co/api/v2/pokemon-species/2/           2
2      venusaur    https://pokeapi.co/api/v2/pokemon-species/3/           3
3    charmander    https://pokeapi.co/api/v2/pokemon-species/4/           4
4    charmeleon    https://pokeapi.co/api/v2/pokemon-species/5/           5
..          ...                                             ...         ...
146     dratini  https://pokeapi.co/api/v2/pokemon-species/147/         147
147   dragonair  https://pokeapi.co/api/v2/pokemon-species/148/         148
148   dragonite  https://pokeapi.co/api/v2/pokemon-species/149/         149
149      mewtwo  https://pokeapi.co/api/v2/pokemon-species/150/         150
150         mew  https://pokeapi.co/api/v2/pokemon-species/151/         151

[151 rows x 3 columns]

In [65]:
with open('../../data/Pokemon Data/generation_1_species_details/pokemon_1_species_details', 'r') as file:
    test_data = json.load(file)

test_df_1 = pd.json_normalize(test_data)
test_df_1.set_index('id', inplace = True)
display(test_df_1)
print(test_df_1.columns)

,base_happiness,capture_rate,egg_groups,evolves_from_species,flavor_text_entries,form_descriptions,forms_switchable,gender_rate,genera,has_gender_differences,...,color.url,evolution_chain.url,generation.name,generation.url,growth_rate.name,growth_rate.url,habitat.name,habitat.url,shape.name,shape.url
id,,,,,,,,,,,,,,,,,,,,,
1,50,45,"[{'name': 'monster', 'url': 'https://pokeapi.c...",None,[{'flavor_text': 'A strange seed was planted o...,[],False,1,"[{'genus': 'たねポケモン', 'language': {'name': 'ja-...",False,...,https://pokeapi.co/api/v2/pokemon-color/5/,https://pokeapi.co/api/v2/evolution-chain/1/,generation-i,https://pokeapi.co/api/v2/generation/1/,medium-slow,https://pokeapi.co/api/v2/growth-rate/4/,grassland,https://pokeapi.co/api/v2/pokemon-habitat/3/,quadruped,https://pokeapi.co/api/v2/pokemon-shape/8/

Index(['base_happiness', 'capture_rate', 'egg_groups', 'evolves_from_species',
       'flavor_text_entries', 'form_descriptions', 'forms_switchable',
       'gender_rate', 'genera', 'has_gender_differences', 'hatch_counter',
       'is_baby', 'is_legendary', 'is_mythical', 'name', 'names', 'order',
       'pal_park_encounters', 'pokedex_numbers', 'varieties', 'color.name',
       'color.url', 'evolution_chain.url', 'generation.name', 'generation.url',
       'growth_rate.name', 'growth_rate.url', 'habitat.name', 'habitat.url',
       'shape.name', 'shape.url'],
      dtype='object')

In [66]:
with open('../../data/Pokemon Data/generation_1_pokemon_details/pokemon_1_details', 'r') as file:
    test_data = json.load(file)

test_df_2 = pd.json_normalize(test_data)
test_df_2.drop(columns = [col for col in test_df_2.columns if "sprites" in col], inplace = True)
test_df_2.set_index('id', inplace = True)
display(test_df_2)
print(test_df_2.columns)

,abilities,base_experience,forms,game_indices,height,held_items,is_default,location_area_encounters,moves,name,order,past_abilities,past_types,stats,types,weight,cries.latest,cries.legacy,species.name,species.url
id,,,,,,,,,,,,,,,,,,,,
1,"[{'ability': {'name': 'overgrow', 'url': 'http...",64,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'game_index': 153, 'version': {'name': 'red'...",7,[],True,https://pokeapi.co/api/v2/pokemon/1/encounters,"[{'move': {'name': 'razor-wind', 'url': 'https...",bulbasaur,1,[],[],"[{'base_stat': 45, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'grass', 'url': ...",69,https://raw.githubusercontent.com/PokeAPI/crie...,https://raw.githubusercontent.com/PokeAPI/crie...,bulbasaur,https://pokeapi.co/api/v2/pokemon-species/1/

Index(['abilities', 'base_experience', 'forms', 'game_indices', 'height',
       'held_items', 'is_default', 'location_area_encounters', 'moves', 'name',
       'order', 'past_abilities', 'past_types', 'stats', 'types', 'weight',
       'cries.latest', 'cries.legacy', 'species.name', 'species.url'],
      dtype='object')

In [67]:
print(test_df_2.iloc[0,-7])
print(test_df_2.iloc[0,-6])

[{'base_stat': 45, 'effort': 0, 'stat': {'name': 'hp', 'url': 'https://pokeapi.co/api/v2/stat/1/'}}, {'base_stat': 49, 'effort': 0, 'stat': {'name': 'attack', 'url': 'https://pokeapi.co/api/v2/stat/2/'}}, {'base_stat': 49, 'effort': 0, 'stat': {'name': 'defense', 'url': 'https://pokeapi.co/api/v2/stat/3/'}}, {'base_stat': 65, 'effort': 1, 'stat': {'name': 'special-attack', 'url': 'https://pokeapi.co/api/v2/stat/4/'}}, {'base_stat': 65, 'effort': 0, 'stat': {'name': 'special-defense', 'url': 'https://pokeapi.co/api/v2/stat/5/'}}, {'base_stat': 45, 'effort': 0, 'stat': {'name': 'speed', 'url': 'https://pokeapi.co/api/v2/stat/6/'}}]
[{'slot': 1, 'type': {'name': 'grass', 'url': 'https://pokeapi.co/api/v2/type/12/'}}, {'slot': 2, 'type': {'name': 'poison', 'url': 'https://pokeapi.co/api/v2/type/4/'}}]

In [68]:
range_of_poke_id = range(gen_1_poke_df['pokemon_id'].min(), gen_1_poke_df['pokemon_id'].max()+1)

In [69]:
def extract_pokemon_habitat(): 
    json_data = {
    pokemon_id: json.load(open(f'../../data/Pokemon Data/generation_1_species_details/pokemon_{pokemon_id}_species_details', 'r'))
    for pokemon_id in range_of_poke_id
    }
    gen_1_poke_df['habitat_name'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['habitat']['name'])

extract_pokemon_habitat()

,name,url,pokemon_id,habitat_name
0,bulbasaur,https://pokeapi.co/api/v2/pokemon-species/1/,1,grassland
1,ivysaur,https://pokeapi.co/api/v2/pokemon-species/2/,2,grassland
2,venusaur,https://pokeapi.co/api/v2/pokemon-species/3/,3,grassland
3,charmander,https://pokeapi.co/api/v2/pokemon-species/4/,4,mountain
4,charmeleon,https://pokeapi.co/api/v2/pokemon-species/5/,5,mountain
...,...,...,...,...
146,dratini,https://pokeapi.co/api/v2/pokemon-species/147/,147,waters-edge
147,dragonair,https://pokeapi.co/api/v2/pokemon-species/148/,148,waters-edge
148,dragonite,https://pokeapi.co/api/v2/pokemon-species/149/,149,waters-edge
149,mewtwo,https://pokeapi.co/api/v2/pokemon-species/150/,150,rare
150,mew,https://pokeapi.co/api/v2/pokemon-species/151/,151,rare

In [70]:
def extract_pokemon_stats_and_types():
    json_data = {
    pokemon_id: json.load(open(f'../../data/Pokemon Data/generation_1_pokemon_details/pokemon_{pokemon_id}_details', 'r'))
    for pokemon_id in range_of_poke_id
    }
    gen_1_poke_df['type_1'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['types'][0]['type']['name'])
    gen_1_poke_df['type_2'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['types'][1]['type']['name'] if len(json_data[x]['types']) > 1 else None)
    gen_1_poke_df['hp_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][0]['base_stat'])
    gen_1_poke_df['attack_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][1]['base_stat'])
    gen_1_poke_df['defense_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][2]['base_stat'])
    gen_1_poke_df['special_attack_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][3]['base_stat'])
    gen_1_poke_df['special_defence_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][4]['base_stat'])
    gen_1_poke_df['speed_stat'] = gen_1_poke_df['pokemon_id'].apply(lambda x: json_data[x]['stats'][5]['base_stat'])
    return 
    
extract_pokemon_stats_and_types()

,name,url,pokemon_id,habitat_name,type_1,type_2,hp_stat,attack_stat,defense_stat,special_attack_stat,special_defence_stat,speed_stat
0,bulbasaur,https://pokeapi.co/api/v2/pokemon-species/1/,1,grassland,grass,poison,45,49,49,65,65,45
1,ivysaur,https://pokeapi.co/api/v2/pokemon-species/2/,2,grassland,grass,poison,60,62,63,80,80,60
2,venusaur,https://pokeapi.co/api/v2/pokemon-species/3/,3,grassland,grass,poison,80,82,83,100,100,80
3,charmander,https://pokeapi.co/api/v2/pokemon-species/4/,4,mountain,fire,None,39,52,43,60,50,65
4,charmeleon,https://pokeapi.co/api/v2/pokemon-species/5/,5,mountain,fire,None,58,64,58,80,65,80
...,...,...,...,...,...,...,...,...,...,...,...,...
146,dratini,https://pokeapi.co/api/v2/pokemon-species/147/,147,waters-edge,dragon,None,41,64,45,50,50,50
147,dragonair,https://pokeapi.co/api/v2/pokemon-species/148/,148,waters-edge,dragon,None,61,84,65,70,70,70
148,dragonite,https://pokeapi.co/api/v2/pokemon-species/149/,149,waters-edge,dragon,flying,91,134,95,100,100,80
149,mewtwo,https://pokeapi.co/api/v2/pokemon-species/150/,150,rare,psychic,None,106,110,90,154,90,130
150,mew,https://pokeapi.co/api/v2/pokemon-species/151/,151,rare,psychic,None,100,100,100,100,100,100

In [ ]:
def calculate_total_stat():

In [71]:
gen_1_poke_df.set_index('pokemon_id', inplace = True)
display(gen_1_poke_df)

,name,url,habitat_name,type_1,type_2,hp_stat,attack_stat,defense_stat,special_attack_stat,special_defence_stat,speed_stat
pokemon_id,,,,,,,,,,,
1,bulbasaur,https://pokeapi.co/api/v2/pokemon-species/1/,grassland,grass,poison,45,49,49,65,65,45
2,ivysaur,https://pokeapi.co/api/v2/pokemon-species/2/,grassland,grass,poison,60,62,63,80,80,60
3,venusaur,https://pokeapi.co/api/v2/pokemon-species/3/,grassland,grass,poison,80,82,83,100,100,80
4,charmander,https://pokeapi.co/api/v2/pokemon-species/4/,mountain,fire,None,39,52,43,60,50,65
5,charmeleon,https://pokeapi.co/api/v2/pokemon-species/5/,mountain,fire,None,58,64,58,80,65,80
...,...,...,...,...,...,...,...,...,...,...,...
147,dratini,https://pokeapi.co/api/v2/pokemon-species/147/,waters-edge,dragon,None,41,64,45,50,50,50
148,dragonair,https://pokeapi.co/api/v2/pokemon-species/148/,waters-edge,dragon,None,61,84,65,70,70,70
149,dragonite,https://pokeapi.co/api/v2/pokemon-species/149/,waters-edge,dragon,flying,91,134,95,100,100,80
150,mewtwo,https://pokeapi.co/api/v2/pokemon-species/150/,rare,psychic,None,106,110,90,154,90,130
151,mew,https://pokeapi.co/api/v2/pokemon-species/151/,rare,psychic,None,100,100,100,100,100,100